### ISSUE TITLE
emoji article trick doesn't work in Chrome on Windows

### ISSUE THREAD

**Issue by Haroenv** [tjvantoll/tjvantoll.github.com#6]
While it does work without setting a font family on Edge and Internet Explorer, I get the black and white version of the emojis both in your demo as in your menu.

> Windows 10
> Chrome 51.0.2704.103 
> Chrome 52.0.2743.116

**Comment by tjvantoll** [comment]
Hey @Haroenv,

It’s a bug that’s actually fixed in Chrome 53. If you try things out in Canary they should work. If you hit any issues there let me know.

**Comment by Haroenv** [comment]
Oh really? That's great
