### ISSUE TITLE
Link to "Writing" section at the home page is broken

### ISSUE THREAD

**Issue by arogachev** [tjvantoll/tjvantoll.github.com#7]
Hi! You have a nice blog! 👍

I noticed one problem with link to "Writing" section at the site's home page. Currently it's `https://www.tjvantoll.com/writing` which leads to "Distortion of contents error" (that's how it's called in Mozilla Firefox at least). Hovewer for example at this page in the top menu it's correct - `https://www.tjvantoll.com/speaking/` So trailing slash is missing.

**Comment by tjvantoll** [comment]
Hey @arogachev. Thanks 😄

I’m actually not able to recreate this error, but the trailing slash is definitely what I should be using so I went ahead and updated that. Thanks for letting me know.
